import type { Theme } from "types/theme";

export const theme = {
    defaultMode: "dark",
    modes: {
        dark: {
            palette: {
                bg: "#0B0E14",
                surface: "#11151E",
                surface2: "#151A25",
                line: "#212837",
                text: "#E8EBF2",
                muted: "#97A0B3",
                faint: "#7A8496",
                accent: "#6FC7FF",
                buttonInk: "#08151F",
                ok: "#7FD88F",
                spot: "#6FC7FF",
                scrim: "#04060A",
                shadow: "#000000",
            },
            tints: {
                soft: 14,
                tagLine: 18,
                liveLine: 35,
                cardLine: 45,
                cardShadow: 22,
                buttonShadow: 40,
                scrim: 74,
                shadow: 60,
                grain: 4,
                glow: 100,
            },
        },
        light: {
            palette: {
                bg: "#F5F7FA",
                surface: "#FFFFFF",
                surface2: "#EDF1F6",
                line: "#D9E0EA",
                text: "#111927",
                muted: "#4E5A6B",
                faint: "#606C7E",
                accent: "#0B66B5",
                buttonInk: "#FFFFFF",
                ok: "#137A3D",
                spot: "#0B589E",
                scrim: "#111927",
                shadow: "#111927",
            },
            tints: {
                soft: 10,
                tagLine: 25,
                liveLine: 40,
                cardLine: 40,
                cardShadow: 16,
                buttonShadow: 35,
                scrim: 46,
                shadow: 28,
                grain: 3,
                glow: 55,
            },
        },
    },
    glow: ["#6FC7FF", "#A78BFA"],
    radius: 14,
    social: { mode: "dark" },
} as const satisfies Theme;
